version: "3"
services:
  deep_learning:
    build: .
    shm_size: 2gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./run.sh:/app/run.sh:ro
      - ./1_training_preprosess_bash:/app/1_training_preprosess_bash
      - /data/P-Prosjekter/15215600_autmatisert_kartlegging_av_barmarksskader/2020_10_balsfjord_rgb.tiff:/app/1_training_preprosess_bash/drone/2020_10_balsfjord_rgb.tiff:ro
      - /data/P-Prosjekter/15215600_autmatisert_kartlegging_av_barmarksskader/2020_10_rjukan_rgb.tif:/app/1_training_preprosess_bash/drone/2020_10_rjukan_rgb.tif:ro
      - /data/P-Prosjekter/15215600_autmatisert_kartlegging_av_barmarksskader/NiB/Balsfjord/Eksport-nib.tif:/app/1_training_preprosess_bash/aerial/Eksport-nib_balsfjord.tif:ro
      - /data/P-Prosjekter/15215600_autmatisert_kartlegging_av_barmarksskader/NiB/Rjukan/Eksport-nib.tif:/app/1_training_preprosess_bash/aerial/Eksport-nib.tif:ro
      - ./2_training_preprocess_python:/app/2_training_preprocess_python
      - ./3_training_python_modules:/app/3_training_python_modules
      - ./4_train:/app/4_train
      - ./model_save_dir:/app/model_save_dir
      - ./5_predict_preprocess_python:/app/5_predict_preprocess_python
      - ./output:/app/output
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      #POSTGRES_PASSWORD: postgres
